# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'reactNativeSift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for reactNativeSift
  pod 'Sift'

 

  target 'reactNativeSiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'reactNativeSift-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for reactNativeSift-tvOS

  target 'reactNativeSift-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
